"""
Django settings for erp project.

Generated by 'django-admin startproject' using Django 2.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
 
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'o1!^+8%@4ntfze2g7q5-=k@^0srx6mee^0u#5(zn+6^wc*068w'

# SECURITY WARNING: don't run with debug turned on in production (True)!
DEBUG = False 

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

INSTALLED_SYSTEM_APPS = [
    #User Structure
    'auth_users.apps.AuthUsersConfig',
    'auth_user_profiles.apps.AuthUserProfilesConfig',
    #Persom Structure
    'persons.apps.PersonsConfig',
    'contact_information.apps.ContactInformationConfig',
    'extra_information.apps.ExtraInformationConfig',
    #Entity Structure
    'entities.apps.EntitiesConfig',
    'entity_activities.apps.EntityActivitiesConfig',
    'entity_types.apps.EntityTypesConfig',
    'entity_classes.apps.EntityClassesConfig',
]

INSTALLED_SYSTEM_THIRD = [
    'rest_framework',
    'phonenumber_field',
]

#ADD ALL THE APPS 
INSTALLED_APPS = INSTALLED_APPS + INSTALLED_SYSTEM_APPS + INSTALLED_SYSTEM_THIRD

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

if DEBUG == False:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'd8fv1fs73u8ctr',
            'USER': 'mgrzioaspxbgpc',
            'PASSWORD': 'be6d2286175755fa3228009a8f6f604b7bfbd344e3f661500392f97382249c78',
            'HOST': 'ec2-54-243-137-182.compute-1.amazonaws.com',
            'PORT': '5432',
        },
        'OPTIONS': {
            'host_is_server': True,
            #'driver': 'ODBC Driver 13 for SQL Server',
        },
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql_psycopg2',
            'NAME': 'QualityGlobalDB',
            'USER': 'postgres',
            'PASSWORD': 'S1st3mas',
            'HOST': '127.0.0.1',
            'PORT': '5432',
        },
        'OPTIONS': {
            'host_is_server': True,
            #'driver': 'ODBC Driver 13 for SQL Server',
        },
    }

# add this
#import dj_database_url
#db_from_env = dj_database_url.config()
#DATABASES['default'].update(db_from_env)
#DATABASES['default']['CONN_MAX_AGE'] = 500


# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

#Config Auth User Model
AUTH_USER_MODEL = 'auth_users.AuthUser'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
