# Generated by Django 2.0.5 on 2018-05-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auth_user_profile', models.OneToOneField(help_text='Auh User Profile | Perfile de Usuario', on_delete=django.db.models.deletion.CASCADE, to='auth_user_profiles.AuthUserProfile')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employees',
                'ordering': ('auth_user_profile',),
            },
        ),
    ]
