# Generated by Django 2.0.5 on 2018-05-20 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='auth_user_profile',
            field=models.OneToOneField(help_text='Auh user profile | Perfile de usuario', on_delete=django.db.models.deletion.CASCADE, to='auth_user_profiles.AuthUserProfile'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Active | Activo'),
        ),
    ]
