# Generated by Django 2.0.5 on 2018-05-20 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_auto_20180520_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='auth_user_profile',
            field=models.OneToOneField(help_text='Auth user profile | Auth perfil de usuario', on_delete=django.db.models.deletion.CASCADE, to='auth_user_profiles.AuthUserProfile'),
        ),
    ]
