# Generated by Django 2.0.5 on 2018-05-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20180520_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['auth_user_profile'], 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='is_active',
            new_name='active',
        ),
    ]
