# Generated by Django 2.0.5 on 2018-05-20 19:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactinformation',
            name='cell_phone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Cell phone | Celular', max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='email',
            field=models.EmailField(db_index=True, help_text='Email | Correo electrónico', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='contactinformation',
            name='telephone',
            field=phonenumber_field.modelfields.PhoneNumberField(db_index=True, help_text='Telephone | Teléfono', max_length=128, unique=True),
        ),
    ]
