# Generated by Django 2.0.5 on 2018-05-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_information', '0002_auto_20180520_1419'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactinformation',
            options={'ordering': ['email', 'cell_phone', 'telephone'], 'verbose_name': 'Contact Information', 'verbose_name_plural': 'Contact Information'},
        ),
    ]
