# Generated by Django 2.0.5 on 2018-05-19 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('observation', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'db_table': 'extra_info',
                'verbose_name': 'Extra Information',
                'verbose_name_plural': 'Extra Information',
            },
        ),
    ]
