# Generated by Django 2.0.5 on 2018-05-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra_information', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='extrainformation',
            options={'ordering': ['description', 'observation'], 'verbose_name': 'Extra Information', 'verbose_name_plural': 'Extra Information'},
        ),
    ]
