# Generated by Django 2.0.5 on 2018-05-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_activities', '0002_auto_20180519_1302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entityactivity',
            options={'ordering': ['name'], 'verbose_name': 'Entity Activity', 'verbose_name_plural': 'Entity Activities'},
        ),
    ]
