# Generated by Django 2.0.5 on 2018-05-19 15:42

import django.core.validators
from django.db import migrations, models
import entity_classes.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntityClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_entity', models.CharField(choices=[(entity_classes.enums.EntityScope('Actividad Econónica'), 'Actividad Econónica'), (entity_classes.enums.EntityScope('Forma Jurídica'), 'Forma Jurídica'), (entity_classes.enums.EntityScope('Tamaño'), 'Tamaño'), (entity_classes.enums.EntityScope('Ámbito de Operación'), 'Ámbito de Operación'), (entity_classes.enums.EntityScope('Composición del Capital'), 'Composición del Capital')], help_text='Scope entity | Ámbito Entidad', max_length=50)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
            ],
            options={
                'ordering': ['scope_entity', 'name'],
                'verbose_name': 'Entity Class',
                'db_table': 'entity_classes',
                'verbose_name_plural': 'Entity Classes',
            },
        ),
    ]
