# Generated by Django 2.0.5 on 2018-05-19 15:44

import django.core.validators
from django.db import migrations, models
import entity_classes.enums


class Migration(migrations.Migration):

    dependencies = [
        ('entity_classes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityclass',
            name='name',
            field=models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='entityclass',
            name='scope_entity',
            field=models.CharField(choices=[(entity_classes.enums.EntityScope('Actividad Econónica'), 'Actividad Econónica'), (entity_classes.enums.EntityScope('Forma Jurídica'), 'Forma Jurídica'), (entity_classes.enums.EntityScope('Tamaño'), 'Tamaño'), (entity_classes.enums.EntityScope('Ámbito de Operación'), 'Ámbito de Operación'), (entity_classes.enums.EntityScope('Composición del Capital'), 'Composición del Capital')], db_index=True, help_text='Scope entity | Ámbito Entidad', max_length=50, unique=True),
        ),
    ]
