# Generated by Django 2.0.5 on 2018-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_classes', '0002_auto_20180519_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityclass',
            name='scope_entity',
            field=models.CharField(choices=[('Actividad Econónica', 'Actividad Econónica'), ('Forma Jurídica', 'Forma Jurídica'), ('Tamaño', 'Tamaño'), ('Ámbito de Operación', 'Ámbito de Operación'), ('Composición del Capital', 'Composición del Capital')], db_index=True, help_text='Scope entity | Ámbito Entidad', max_length=50),
        ),
    ]
