# Generated by Django 2.0.5 on 2018-05-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_classes', '0004_auto_20180519_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entityclass',
            name='entity_scope',
            field=models.CharField(choices=[('Actividad Econónica', 'Actividad Econónica'), ('Ámbito de Operación', 'Ámbito de Operación'), ('Composición del Capital', 'Composición del Capital'), ('Forma Jurídica', 'Forma Jurídica'), ('Tamaño', 'Tamaño')], db_index=True, help_text='Entity Scope | Ámbito Entidad', max_length=50),
        ),
    ]
