# Generated by Django 2.0.5 on 2018-05-19 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity_types', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entitytype',
            name='initials',
            field=models.CharField(db_index=True, help_text='Initials | Iniciales', max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='entitytype',
            name='name',
            field=models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
