# Generated by Django 2.0.5 on 2018-05-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity_types', '0002_auto_20180519_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitytype',
            options={'ordering': ['name', 'initials'], 'verbose_name': 'Entity Type', 'verbose_name_plural': 'Entity Types'},
        ),
    ]
