# Generated by Django 2.0.5 on 2018-05-19 15:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity_activities', '0001_initial'),
        ('entity_types', '0001_initial'),
        ('entity_classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('slogan', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('initials', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)])),
                ('logo', models.ImageField(blank=True, default=None, null=True, upload_to='image/entities/')),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('entity_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_activities.EntityActivity')),
                ('entity_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_classes.EntityClass')),
                ('entity_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_types.EntityType')),
            ],
            options={
                'verbose_name': 'Entity',
                'db_table': 'entities',
                'verbose_name_plural': 'Entities',
            },
        ),
    ]
