# Generated by Django 2.0.5 on 2018-05-20 23:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['entity_class', 'entity_type', 'entity_activity', 'name'], 'verbose_name': 'Entity', 'verbose_name_plural': 'Entities'},
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_activity',
            field=models.ForeignKey(blank=True, help_text='Entity activity | Actividad de la entidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_activities.EntityActivity'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_class',
            field=models.ForeignKey(blank=True, help_text='Entity class | Clase de la entidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_classes.EntityClass'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.ForeignKey(blank=True, help_text='Entity type | Tipo de la entidad', null=True, on_delete=django.db.models.deletion.SET_NULL, to='entity_types.EntityType'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='initials',
            field=models.CharField(blank=True, db_index=True, help_text='Initials | Iniciales', max_length=20, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='logo',
            field=models.ImageField(blank=True, default=None, help_text='Logo | logo', null=True, upload_to='image/entities/'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='entity',
            name='slogan',
            field=models.CharField(blank=True, db_index=True, help_text='Slogan | Slogan', max_length=100, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
