# Generated by Django 2.0.5 on 2018-05-19 15:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import persons.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact_information', '0001_initial'),
        ('extra_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthUserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('last_name', models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('mother_last_name', models.CharField(db_index=True, max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)])),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[(persons.enums.Gender('Male'), 'Male'), (persons.enums.Gender('Female'), 'Female')], max_length=6)),
                ('marital_status', models.CharField(choices=[(persons.enums.MaritalStatus('Single'), 'Single'), (persons.enums.MaritalStatus('Legal'), 'Legal'), (persons.enums.MaritalStatus('Divorced'), 'Divorced'), (persons.enums.MaritalStatus('Separated'), 'Separated'), (persons.enums.MaritalStatus('Widower'), 'Widower')], max_length=9)),
                ('blood_group', models.CharField(choices=[(persons.enums.BloodGroup('A+'), 'A+'), (persons.enums.BloodGroup('A-'), 'A-'), (persons.enums.BloodGroup('B+'), 'B+'), (persons.enums.BloodGroup('B-'), 'B-'), (persons.enums.BloodGroup('AB+'), 'AB+'), (persons.enums.BloodGroup('AB-'), 'AB-'), (persons.enums.BloodGroup('O+'), 'O+'), (persons.enums.BloodGroup('O-'), 'O-')], max_length=9)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('contact_information', models.ManyToManyField(blank=True, to='contact_information.ContactInformation')),
                ('extra_information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra_information.ExtraInformation')),
            ],
            options={
                'db_table': 'auth_user_profiles',
                'verbose_name': 'Auth User Profile',
                'verbose_name_plural': 'Auth User Profiles',
            },
        ),
    ]
