# Generated by Django 2.0.5 on 2018-05-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth_user_profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact_information', '0001_initial'),
        ('extra_information', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserprofile',
            name='auth_user',
            field=models.OneToOneField(help_text='Auth user | Auth usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='contact_information',
            field=models.ManyToManyField(blank=True, help_text='Contact information | Informarción de contacto', to='contact_information.ContactInformation'),
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='extra_information',
            field=models.ForeignKey(blank=True, help_text='Extra information | Informarción extra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra_information.ExtraInformation'),
        ),
    ]
