# Generated by Django 2.0.5 on 2018-05-20 19:06

import django.core.validators
from django.db import migrations, models
import persons.enums


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuserprofile',
            name='photography',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='image/persons/'),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='birthday',
            field=models.DateField(help_text='birthday | Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[(persons.enums.BloodGroup('A+'), 'A+'), (persons.enums.BloodGroup('A-'), 'A-'), (persons.enums.BloodGroup('B+'), 'B+'), (persons.enums.BloodGroup('B-'), 'B-'), (persons.enums.BloodGroup('AB+'), 'AB+'), (persons.enums.BloodGroup('AB-'), 'AB-'), (persons.enums.BloodGroup('O+'), 'O+'), (persons.enums.BloodGroup('O-'), 'O-')], help_text='Blood group | Grupo sanguíneo', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='gender',
            field=models.CharField(choices=[(persons.enums.Gender('Masculino'), 'Masculino'), (persons.enums.Gender('Femenino'), 'Femenino'), (persons.enums.Gender('Otros'), 'Otros')], help_text='Gender | Género', max_length=6),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='last_name',
            field=models.CharField(db_index=True, help_text='Last name | Apellido paterno', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='marital_status',
            field=models.CharField(choices=[(persons.enums.MaritalStatus('Soltero'), 'Soltero'), (persons.enums.MaritalStatus('Casado'), 'Casado'), (persons.enums.MaritalStatus('Divorciado'), 'Divorciado'), (persons.enums.MaritalStatus('Separado'), 'Separado'), (persons.enums.MaritalStatus('Viudo'), 'Viudo')], help_text='Marital status | Estado marital o civil', max_length=9),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='mother_last_name',
            field=models.CharField(db_index=True, help_text='Mother last name | Apellido materno', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='name',
            field=models.CharField(db_index=True, help_text='Name | Nombre', max_length=100, unique=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
