# Generated by Django 2.0.5 on 2018-05-20 19:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth_user_profiles', '0002_auto_20180520_1406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuserprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='authuserprofile',
            name='auth_user',
            field=models.OneToOneField(default='', help_text='Auth user | Auth usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='active',
            field=models.BooleanField(default=True, help_text='Active | Activo'),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='contact_information',
            field=models.ManyToManyField(blank=True, help_text='Contact information | Informarción de contacto', to='contact_information.ContactInformation'),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='extra_information',
            field=models.ForeignKey(blank=True, help_text='Extra information | Informarción extra', null=True, on_delete=django.db.models.deletion.SET_NULL, to='extra_information.ExtraInformation'),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='photography',
            field=models.ImageField(blank=True, default=None, help_text='Photography | Fotografía', null=True, upload_to='image/persons/'),
        ),
    ]
