# Generated by Django 2.0.5 on 2018-05-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_profiles', '0003_auto_20180520_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserprofile',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], help_text='Blood group | Grupo sanguíneo', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros')], help_text='Gender | Género', max_length=6),
        ),
        migrations.AlterField(
            model_name='authuserprofile',
            name='marital_status',
            field=models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Divorciado', 'Divorciado'), ('Separado', 'Separado'), ('Viudo', 'Viudo')], help_text='Marital status | Estado marital o civil', max_length=9),
        ),
    ]
