# Generated by Django 2.0.5 on 2018-05-20 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_user_profiles', '0004_auto_20180520_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authuserprofile',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otros', 'Otros')], help_text='Gender | Género', max_length=9),
        ),
    ]
